### ISSUE TITLE
Improve last updated tracking

### ISSUE THREAD

**Issue by alexhad6** [PainterQubits/paramdb#170]
Track last updated timestamps on all levels:

- [x] Merge `Param` and `Struct` into `ParamDataclass`
- [x] Add internal last updated property to `ParamDataclass`, `ParamDict`, and `ParamList`, which is updated when any properties are added, updated, or deleted
- [x] Update `last_updated` to return the most recent timestamp between self and children

**Comment by alexhad6** [comment]
- [ ] Update tests
- [ ] Update docs
- [ ] Update CHANGELOG
